apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-deployment
  labels:
    app: brain
spec:
  replicas: 3
  selector:
    matchLabels:
      app: brain
  template:
    metadata:
      labels:
        app: brain
    spec:
      containers:
      - name: brain-container
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"