apiVersion: v1
kind: Service
metadata:
  name: brain-service
  labels:
    app: brain
spec:
  type: LoadBalancer
  selector:
    app: brain
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80